schema_version: 1

context:
  version: "0.5.1"
  python_min: "3.10"

package:
  name: rucio-mcp
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/7f/21/e8052372f06d15edff44c1a35440fa18d0c9c2cf755f19006acd315205fb/rucio_mcp-${{ version }}.tar.gz
  sha256: 79de24b1c2ec2fc5ab68c1c7f5350be72935b24d6827ea449de1a7e5a438a51d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - rucio-mcp=rucio_mcp.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - rucio-clients >=35.0.0
    - mcp >=1.0
    - prometheus_client >=0.20
    - ca-policy-lcg  # for cert
    - voms # for voms-client
    - voms-lsc # for voms-certs
    - __unix  # see https://github.com/rucio/rucio/issues/8461?reload=1

tests:
  - python:
      imports:
        - rucio_mcp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - rucio-mcp --help

about:
  summary: An MCP server that exposes Rucio distributed data management operations as tools for LLMs.
  homepage: https://rucio-mcp.readthedocs.io/en/latest/
  repository: https://github.com/kratsg/rucio-mcp
  documentation: https://rucio-mcp.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
