schema_version: 1

context:
  version: "0.9.3"

package:
  name: rucio-mcp
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/4a/d7/e5c6c6067b91d19af5a080dacb8b03a76daabecc881f284ac71467b6c71a/rucio_mcp-${{ version }}.tar.gz
  sha256: 9a817a097ba09b5ef0a4ca5eebedd971c698f5efde18280d3d7ad76636a3b190

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - rucio-mcp=rucio_mcp.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - rucio-clients >=35.0.0
    - httpx2 >=2.0.0
    - mcp >=2.0.0,<3
    - prometheus_client >=0.20
    - ca-policy-lcg  # for cert
    - voms # for voms-client
    - voms-lsc # for voms-certs
    - __unix  # see https://github.com/rucio/rucio/issues/8461?reload=1
    - af-credentials >=0.2.0

tests:
  - python:
      imports:
        - rucio_mcp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - rucio-mcp --help

about:
  summary: An MCP server that exposes Rucio distributed data management operations as tools for LLMs.
  homepage: https://rucio-mcp.readthedocs.io/en/latest/
  repository: https://github.com/kratsg/rucio-mcp
  documentation: https://rucio-mcp.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
