schema_version: 1

context:
  version: "0.9.1"

package:
  name: rucio-mcp
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/22/7f/5d6d122e91c2af51f6b0fac95b11891fdf4c790d0c55be2b88f90a6de900/rucio_mcp-${{ version }}.tar.gz
  sha256: 9708f09c4b5c7622a6685db7256e01df8b5eb67974ef4b6e5669c112de35348b

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - rucio-mcp=rucio_mcp.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - rucio-clients >=35.0.0
    - httpx2 >=2.0.0
    - mcp >=2.0.0,<3
    - prometheus_client >=0.20
    - ca-policy-lcg  # for cert
    - voms # for voms-client
    - voms-lsc # for voms-certs
    - __unix  # see https://github.com/rucio/rucio/issues/8461?reload=1
    - af-credentials >=0.2.0

tests:
  - python:
      imports:
        - rucio_mcp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - rucio-mcp --help

about:
  summary: An MCP server that exposes Rucio distributed data management operations as tools for LLMs.
  homepage: https://rucio-mcp.readthedocs.io/en/latest/
  repository: https://github.com/kratsg/rucio-mcp
  documentation: https://rucio-mcp.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
